name: null
favicon: null
layout_spectrum: 0.8142509423196316
typography_spectrum: 0.9884031703695655
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8738954022992402
  lightness: 0.000876372680068016
  saturation: 0.5789857388008386
  rhythmicContrast: 0.8439816744066775
purpose: []
